const precios = {
  comunYUTCGR: [
    { material: "SERIE 1", precio: 798 },
    { material: "SERIE 2", precio: 833 },
    { material: "SERIE 3", precio: 869 },
    { material: "SERIE 4", precio: 904 },
    { material: "SERIE 5", precio: 956 },
    { material: "SERIE 6", precio: 1010 },
    { material: "SERIE 7", precio: 1080 },
    { material: "PROMO", precio: 1205 },
    { material: "PIEL A", precio: 1277 },
    { material: "PIEL B", precio: 1378 },
    { material: "PIEL C", precio: 1552 },
    { material: "PIEL D", precio: 1753 },
  ],
  comunYUTCMA: [
    { material: "SERIE 1", precio: 827 },
    { material: "SERIE 2", precio: 862 },
    { material: "SERIE 3", precio: 898 },
    { material: "SERIE 4", precio: 935 },
    { material: "SERIE 5", precio: 990 },
    { material: "SERIE 6", precio: 1044 },
    { material: "SERIE 7", precio: 1116 },
    { material: "PROMO", precio: 1114 },
    { material: "PIEL A", precio: 1181 },
    { material: "PIEL B", precio: 1275 },
    { material: "PIEL C", precio: 1436 },
    { material: "PIEL D", precio: 1625 },
  ],
  comunYUTCME: [
    { material: "SERIE 1", precio: 877 },
    { material: "SERIE 2", precio: 915 },
    { material: "SERIE 3", precio: 955 },
    { material: "SERIE 4", precio: 955 },
    { material: "SERIE 5", precio: 1055 },
    { material: "SERIE 6", precio: 1114 },
    { material: "SERIE 7", precio: 1194 },
    { material: "PROMO", precio: 1363 },
    { material: "PIEL A", precio: 1450 },
    { material: "PIEL B", precio: 1572 },
    { material: "PIEL C", precio: 1781 },
    { material: "PIEL D", precio: 2024 },
  ],
  comunYUTMGR: [
    { material: "SERIE 1", precio: 823 },
    { material: "SERIE 2", precio: 852 },
    { material: "SERIE 3", precio: 881 },
    { material: "SERIE 4", precio: 910 },
    { material: "SERIE 5", precio: 954 },
    { material: "SERIE 6", precio: 998 },
    { material: "SERIE 7", precio: 998 },
    { material: "PROMO", precio: 1066 },
    { material: "PIEL A", precio: 1117 },
    { material: "PIEL B", precio: 1190 },
    { material: "PIEL C", precio: 1313 },
    { material: "PIEL D", precio: 1457 },
  ],
  comunYUTMGRDI: [
    { material: "SERIE 1", precio: 921 },
    { material: "SERIE 2", precio: 954 },
    { material: "SERIE 3", precio: 986 },
    { material: "SERIE 4", precio: 1019 },
    { material: "SERIE 5", precio: 1067 },
    { material: "SERIE 6", precio: 1116 },
    { material: "SERIE 7", precio: 1181 },
    { material: "PROMO", precio: 1302 },
    { material: "PIEL A", precio: 1375 },
    { material: "PIEL B", precio: 1477 },
    { material: "PIEL C", precio: 1654 },
    { material: "PIEL D", precio: 1859 },
  ],
  comunYUTMMADI: [
    { material: "SERIE 1", precio: 967 },
    { material: "SERIE 2", precio: 1000 },
    { material: "SERIE 3", precio: 1033 },
    { material: "SERIE 4", precio: 1067 },
    { material: "SERIE 5", precio: 1117 },
    { material: "SERIE 6", precio: 1167 },
    { material: "SERIE 7", precio: 1235 },
    { material: "PROMO", precio: 1344 },
    { material: "PIEL A", precio: 1418 },
    { material: "PIEL B", precio: 1521 },
    { material: "PIEL C", precio: 1696 },
    { material: "PIEL D", precio: 1902 },
  ],
  comunYUTMME: [
    { material: "SERIE 1", precio: 909 },
    { material: "SERIE 2", precio: 939 },
    { material: "SERIE 3", precio: 969 },
    { material: "SERIE 4", precio: 1000 },
    { material: "SERIE 5", precio: 1044 },
    { material: "SERIE 6", precio: 1090 },
    { material: "SERIE 7", precio: 1150 },
    { material: "PROMO", precio: 1232 },
    { material: "PIEL A", precio: 1296 },
    { material: "PIEL B", precio: 1387 },
    { material: "PIEL C", precio: 1542 },
    { material: "PIEL D", precio: 1725 },
  ],
  comunYUTMMEDI: [
    { material: "SERIE 1", precio: 1003 },
    { material: "SERIE 2", precio: 1039 },
    { material: "SERIE 3", precio: 1074 },
    { material: "SERIE 4", precio: 1109 },
    { material: "SERIE 5", precio: 1162 },
    { material: "SERIE 6", precio: 1214 },
    { material: "SERIE 7", precio: 1285 },
    { material: "PROMO", precio: 1411 },
    { material: "PIEL A", precio: 1491 },
    { material: "PIEL B", precio: 1602 },
    { material: "PIEL C", precio: 1793 },
    { material: "PIEL D", precio: 2016 },
  ],
  comunYUTMXLDI: [
    { material: "SERIE 1", precio: 1049 },
    { material: "SERIE 2", precio: 1084 },
    { material: "SERIE 3", precio: 1119 },
    { material: "SERIE 4", precio: 1155 },
    { material: "SERIE 5", precio: 1207 },
    { material: "SERIE 6", precio: 1260 },
    { material: "SERIE 7", precio: 1330 },
    { material: "PROMO", precio: 1454 },
    { material: "PIEL A", precio: 1533 },
    { material: "PIEL B", precio: 1644 },
    { material: "PIEL C", precio: 1835 },
    { material: "PIEL D", precio: 2058 },
  ],
  comunYUTMXL: [
    { material: "SERIE 1", precio: 954 },
    { material: "SERIE 2", precio: 985 },
    { material: "SERIE 3", precio: 1015 },
    { material: "SERIE 4", precio: 1045 },
    { material: "SERIE 5", precio: 1090 },
    { material: "SERIE 6", precio: 1135 },
    { material: "SERIE 7", precio: 1196 },
    { material: "PROMO", precio: 1275 },
    { material: "PIEL A", precio: 1340 },
    { material: "PIEL B", precio: 1431 },
    { material: "PIEL C", precio: 1586 },
    { material: "PIEL D", precio: 1767 },
  ],
  comunYUTRA: [
    { material: "SERIE 1", precio: 919 },
    { material: "SERIE 2", precio: 956 },
    { material: "SERIE 3", precio: 994 },
    { material: "SERIE 4", precio: 1033 },
    { material: "SERIE 5", precio: 1090 },
    { material: "SERIE 6", precio: 1147 },
    { material: "SERIE 7", precio: 1222 },
    { material: "PROMO", precio: 1390 },
    { material: "PIEL A", precio: 1473 },
    { material: "PIEL B", precio: 1589 },
    { material: "PIEL C", precio: 1789 },
    { material: "PIEL D", precio: 2021 },
  ],
  comunYUTRT: [
    { material: "SERIE 1", precio: 1270 },
    { material: "SERIE 2", precio: 1327 },
    { material: "SERIE 3", precio: 1385 },
    { material: "SERIE 4", precio: 1442 },
    { material: "SERIE 5", precio: 1529 },
    { material: "SERIE 6", precio: 1615 },
    { material: "SERIE 7", precio: 1731 },
    { material: "PROMO", precio: 1982 },
    { material: "PIEL A", precio: 2103 },
    { material: "PIEL B", precio: 2272 },
    { material: "PIEL C", precio: 2563 },
    { material: "PIEL D", precio: 2901 },
  ],
  comunYUTTGR: [
    { material: "SERIE 1", precio: 733 },
    { material: "SERIE 2", precio: 764 },
    { material: "SERIE 3", precio: 795 },
    { material: "SERIE 4", precio: 825 },
    { material: "SERIE 5", precio: 871 },
    { material: "SERIE 6", precio: 918 },
    { material: "SERIE 7", precio: 979 },
    { material: "PROMO", precio: 1114 },
    { material: "PIEL A", precio: 1181 },
    { material: "PIEL B", precio: 1275 },
    { material: "PIEL C", precio: 1436 },
    { material: "PIEL D", precio: 1625 },
  ],
  comunYUTTMA: [
    { material: "SERIE 1", precio: 759 },
    { material: "SERIE 2", precio: 791 },
    { material: "SERIE 3", precio: 823 },
    { material: "SERIE 4", precio: 855 },
    { material: "SERIE 5", precio: 903 },
    { material: "SERIE 6", precio: 950 },
    { material: "SERIE 7", precio: 1013 },
    { material: "PROMO", precio: 1151 },
    { material: "PIEL A", precio: 1221 },
    { material: "PIEL B", precio: 1319 },
    { material: "PIEL C", precio: 1487 },
    { material: "PIEL D", precio: 1682 },
  ],
};
/*----------------------LINO----------------------*/
const preciosLino = {
  comunLINCGR: [
    { material: "SERIE 1", precio: 732 },
    { material: "SERIE 2", precio: 767 },
    { material: "SERIE 3", precio: 801 },
    { material: "SERIE 4", precio: 837 },
    { material: "SERIE 5", precio: 890 },
    { material: "SERIE 6", precio: 943 },
    { material: "SERIE 7", precio: 1013 },
    { material: "PROMO", precio: 1101 },
    { material: "PIEL A", precio: 1171 },
    { material: "PIEL B", precio: 1268 },
    { material: "PIEL C", precio: 1435 },
    { material: "PIEL D", precio: 1630 },
  ],
  comunLINCMA: [
    { material: "SERIE 1", precio: 757 },
    { material: "SERIE 2", precio: 793 },
    { material: "SERIE 3", precio: 830 },
    { material: "SERIE 4", precio: 866 },
    { material: "SERIE 5", precio: 921 },
    { material: "SERIE 6", precio: 976 },
    { material: "SERIE 7", precio: 1048 },
    { material: "PROMO", precio: 1210 },
    { material: "PIEL A", precio: 1293 },
    { material: "PIEL B", precio: 1409 },
    { material: "PIEL C", precio: 1609 },
    { material: "PIEL D", precio: 1841 },
  ],
  comunLINCMD: [
    { material: "SERIE 1", precio: 675 },
    { material: "SERIE 2", precio: 707 },
    { material: "SERIE 3", precio: 738 },
    { material: "SERIE 4", precio: 768 },
    { material: "SERIE 5", precio: 816 },
    { material: "SERIE 6", precio: 863 },
    { material: "SERIE 7", precio: 926 },
    { material: "PROMO", precio: 1067 },
    { material: "PIEL A", precio: 1135 },
    { material: "PIEL B", precio: 1231 },
    { material: "PIEL C", precio: 1395 },
    { material: "PIEL D", precio: 1587 },
  ],
  comunLINCME: [
    { material: "SERIE 1", precio: 798 },
    { material: "SERIE 2", precio: 838 },
    { material: "SERIE 3", precio: 878 },
    { material: "SERIE 4", precio: 917 },
    { material: "SERIE 5", precio: 977 },
    { material: "SERIE 6", precio: 1036 },
    { material: "SERIE 7", precio: 1115 },
    { material: "PROMO", precio: 1285 },
    { material: "PIEL A", precio: 1373 },
    { material: "PIEL B", precio: 1493 },
    { material: "PIEL C", precio: 1702 },
    { material: "PIEL D", precio: 1945 },
  ],
  comunLINMGR: [
    { material: "SERIE 1", precio: 756 },
    { material: "SERIE 2", precio: 785 },
    { material: "SERIE 3", precio: 814 },
    { material: "SERIE 4", precio: 844 },
    { material: "SERIE 5", precio: 887 },
    { material: "SERIE 6", precio: 930 },
    { material: "SERIE 7", precio: 988 },
    { material: "PROMO", precio: 970 },
    { material: "PIEL A", precio: 1020 },
    { material: "PIEL B", precio: 1090 },
    { material: "PIEL C", precio: 1211 },
    { material: "PIEL D", precio: 1351 },
  ],
  comunLINMGRDI: [
    { material: "SERIE 1", precio: 854 },
    { material: "SERIE 2", precio: 887 },
    { material: "SERIE 3", precio: 919 },
    { material: "SERIE 4", precio: 952 },
    { material: "SERIE 5", precio: 1000 },
    { material: "SERIE 6", precio: 1049 },
    { material: "SERIE 7", precio: 1114 },
    { material: "PROMO", precio: 1197 },
    { material: "PIEL A", precio: 1268 },
    { material: "PIEL B", precio: 1368 },
    { material: "PIEL C", precio: 1538 },
    { material: "PIEL D", precio: 1736 },
  ],
  comunLINMMA: [
    { material: "SERIE 1", precio: 796 },
    { material: "SERIE 2", precio: 825 },
    { material: "SERIE 3", precio: 854 },
    { material: "SERIE 4", precio: 884 },
    { material: "SERIE 5", precio: 927 },
    { material: "SERIE 6", precio: 970 },
    { material: "SERIE 7", precio: 1028 },
    { material: "PROMO", precio: 1035 },
    { material: "PIEL A", precio: 1089 },
    { material: "PIEL B", precio: 1167 },
    { material: "PIEL C", precio: 1293 },
    { material: "PIEL D", precio: 1443 },
  ],
  comunLINMMADI: [
    { material: "SERIE 1", precio: 897 },
    { material: "SERIE 2", precio: 931 },
    { material: "SERIE 3", precio: 964 },
    { material: "SERIE 4", precio: 999 },
    { material: "SERIE 5", precio: 1049 },
    { material: "SERIE 6", precio: 1099 },
    { material: "SERIE 7", precio: 1166 },
    { material: "PROMO", precio: 1254 },
    { material: "PIEL A", precio: 1328 },
    { material: "PIEL B", precio: 1431 },
    { material: "PIEL C", precio: 1606 },
    { material: "PIEL D", precio: 1811 },
  ],
  comunLINMMD: [
    { material: "SERIE 1", precio: 661 },
    { material: "SERIE 2", precio: 684 },
    { material: "SERIE 3", precio: 707 },
    { material: "SERIE 4", precio: 728 },
    { material: "SERIE 5", precio: 763 },
    { material: "SERIE 6", precio: 796 },
    { material: "SERIE 7", precio: 840 },
    { material: "PROMO", precio: 952 },
    { material: "PIEL A", precio: 1001 },
    { material: "PIEL B", precio: 1069 },
    { material: "PIEL C", precio: 1187 },
    { material: "PIEL D", precio: 1324 },
  ],
  comunLINMMDI: [
    { material: "SERIE 1", precio: 768 },
    { material: "SERIE 2", precio: 800 },
    { material: "SERIE 3", precio: 832 },
    { material: "SERIE 4", precio: 864 },
    { material: "SERIE 5", precio: 911 },
    { material: "SERIE 6", precio: 959 },
    { material: "SERIE 7", precio: 1023 },
    { material: "PROMO", precio: 1170 },
    { material: "PIEL A", precio: 1239 },
    { material: "PIEL B", precio: 1336 },
    { material: "PIEL C", precio: 1504 },
    { material: "PIEL D", precio: 1699 },
  ],
  comunLINMME: [
    { material: "SERIE 1", precio: 839 },
    { material: "SERIE 2", precio: 869 },
    { material: "SERIE 3", precio: 899 },
    { material: "SERIE 4", precio: 929 },
    { material: "SERIE 5", precio: 975 },
    { material: "SERIE 6", precio: 1020 },
    { material: "SERIE 7", precio: 1081 },
    { material: "PROMO", precio: 1132 },
    { material: "PIEL A", precio: 1195 },
    { material: "PIEL B", precio: 1284 },
    { material: "PIEL C", precio: 1436 },
    { material: "PIEL D", precio: 1641 },
  ],
  comunLINMMEDI: [
    { material: "SERIE 1", precio: 934 },
    { material: "SERIE 2", precio: 969 },
    { material: "SERIE 3", precio: 1004 },
    { material: "SERIE 4", precio: 1039 },
    { material: "SERIE 5", precio: 1092 },
    { material: "SERIE 6", precio: 1145 },
    { material: "SERIE 7", precio: 1215 },
    { material: "PROMO", precio: 1304 },
    { material: "PIEL A", precio: 1381 },
    { material: "PIEL B", precio: 1489 },
    { material: "PIEL C", precio: 1674 },
    { material: "PIEL D", precio: 1889 },
  ],
  comunLINMXL: [
    { material: "SERIE 1", precio: 885 },
    { material: "SERIE 2", precio: 914 },
    { material: "SERIE 3", precio: 945 },
    { material: "SERIE 4", precio: 975 },
    { material: "SERIE 5", precio: 1020 },
    { material: "SERIE 6", precio: 1066 },
    { material: "SERIE 7", precio: 1126 },
    { material: "PROMO", precio: 1196 },
    { material: "PIEL A", precio: 1261 },
    { material: "PIEL B", precio: 1351 },
    { material: "PIEL C", precio: 1507 },
    { material: "PIEL D", precio: 1688 },
  ],
  comunLINMXLDI: [
    { material: "SERIE 1", precio: 979 },
    { material: "SERIE 2", precio: 1015 },
    { material: "SERIE 3", precio: 1050 },
    { material: "SERIE 4", precio: 1084 },
    { material: "SERIE 5", precio: 1138 },
    { material: "SERIE 6", precio: 1190 },
    { material: "SERIE 7", precio: 1261 },
    { material: "PROMO", precio: 1367 },
    { material: "PIEL A", precio: 1444 },
    { material: "PIEL B", precio: 1554 },
    { material: "PIEL C", precio: 1742 },
    { material: "PIEL D", precio: 1961 },
  ],
  comunLINRA: [
    { material: "SERIE 1", precio: 767 },
    { material: "SERIE 2", precio: 804 },
    { material: "SERIE 3", precio: 840 },
    { material: "SERIE 4", precio: 877 },
    { material: "SERIE 5", precio: 931 },
    { material: "SERIE 6", precio: 986 },
    { material: "SERIE 7", precio: 1058 },
    { material: "PROMO", precio: 1220 },
    { material: "PIEL A", precio: 1300 },
    { material: "PIEL B", precio: 1411 },
    { material: "PIEL C", precio: 1602 },
    { material: "PIEL D", precio: 1824 },
  ],
  comunLINRDI: [
    { material: "SERIE 1", precio: 1208 },
    { material: "SERIE 2", precio: 1265 },
    { material: "SERIE 3", precio: 1324 },
    { material: "SERIE 4", precio: 1381 },
    { material: "SERIE 5", precio: 1467 },
    { material: "SERIE 6", precio: 1554 },
    { material: "SERIE 7", precio: 1669 },
    { material: "PROMO", precio: 1816 },
    { material: "PIEL A", precio: 1931 },
    { material: "PIEL B", precio: 2092 },
    { material: "PIEL C", precio: 2368 },
    { material: "PIEL D", precio: 2689 },
  ],
  comunLINRTDI: [
    { material: "SERIE 1", precio: 1208 },
    { material: "SERIE 2", precio: 1265 },
    { material: "SERIE 3", precio: 1324 },
    { material: "SERIE 4", precio: 1381 },
    { material: "SERIE 5", precio: 1467 },
    { material: "SERIE 6", precio: 1554 },
    { material: "SERIE 7", precio: 1669 },
    { material: "PROMO", precio: 1816 },
    { material: "PIEL A", precio: 1931 },
    { material: "PIEL B", precio: 2092 },
    { material: "PIEL C", precio: 2368 },
    { material: "PIEL D", precio: 2689 },
  ],
  comunLINTGRDI: [
    { material: "SERIE 1", precio: 658 },
    { material: "SERIE 2", precio: 689 },
    { material: "SERIE 3", precio: 719 },
    { material: "SERIE 4", precio: 750 },
    { material: "SERIE 5", precio: 796 },
    { material: "SERIE 6", precio: 842 },
    { material: "SERIE 7", precio: 904 },
    { material: "PROMO", precio: 1039 },
    { material: "PIEL A", precio: 1106 },
    { material: "PIEL B", precio: 1199 },
    { material: "PIEL C", precio: 1361 },
    { material: "PIEL D", precio: 1549 },
  ],
  comunLINTMADI: [
    { material: "SERIE 1", precio: 683 },
    { material: "SERIE 2", precio: 715 },
    { material: "SERIE 3", precio: 747 },
    { material: "SERIE 4", precio: 779 },
    { material: "SERIE 5", precio: 825 },
    { material: "SERIE 6", precio: 873 },
    { material: "SERIE 7", precio: 937 },
    { material: "PROMO", precio: 1075 },
    { material: "PIEL A", precio: 1145 },
    { material: "PIEL B", precio: 1243 },
    { material: "PIEL C", precio: 1410 },
    { material: "PIEL D", precio: 1605 },
  ],
};

/*---------------PRECIOS AGORA----------------------*/
const preciosAgora = {
  comunAGOCGR: [
    { material: "SERIE 1", precio: 885 },
    { material: "SERIE 2", precio: 914 },
    { material: "SERIE 3", precio: 943 },
    { material: "SERIE 4", precio: 971 },
    { material: "SERIE 5", precio: 1016 },
    { material: "SERIE 6", precio: 943 },
    { material: "SERIE 7", precio: 1013 },
  ],
  comunAGOCMA: [
    { material: "SERIE 1", precio: 919 },
    { material: "SERIE 2", precio: 950 },
    { material: "SERIE 3", precio: 980 },
    { material: "SERIE 4", precio: 1011 },
    { material: "SERIE 5", precio: 1058 },
    { material: "SERIE 6", precio: 1104 },
    { material: "SERIE 7", precio: 1165 },
  ],
  comunAGOCME: [
    { material: "SERIE 1", precio: 974 },
    { material: "SERIE 2", precio: 1008 },
    { material: "SERIE 3", precio: 1041 },
    { material: "SERIE 4", precio: 1074 },
    { material: "SERIE 5", precio: 1124 },
    { material: "SERIE 6", precio: 1175 },
    { material: "SERIE 7", precio: 1241 },
  ],
  comunAGOMGR: [
    { material: "SERIE 1", precio: 516 },
    { material: "SERIE 2", precio: 532 },
    { material: "SERIE 3", precio: 548 },
    { material: "SERIE 4", precio: 564 },
    { material: "SERIE 5", precio: 589 },
    { material: "SERIE 6", precio: 613 },
    { material: "SERIE 7", precio: 646 },
  ],
  comunAGOMGRDI: [
    { material: "SERIE 1", precio: 651 },
    { material: "SERIE 2", precio: 676 },
    { material: "SERIE 3", precio: 701 },
    { material: "SERIE 4", precio: 726 },
    { material: "SERIE 5", precio: 764 },
    { material: "SERIE 6", precio: 801 },
    { material: "SERIE 7", precio: 852 },
  ],
  comunAGOMMA: [
    { material: "SERIE 1", precio: 546 },
    { material: "SERIE 2", precio: 563 },
    { material: "SERIE 3", precio: 580 },
    { material: "SERIE 4", precio: 596 },
    { material: "SERIE 5", precio: 621 },
    { material: "SERIE 6", precio: 646 },
    { material: "SERIE 7", precio: 681 },
  ],
  comunAGOMMADI: [
    { material: "SERIE 1", precio: 670 },
    { material: "SERIE 2", precio: 697 },
    { material: "SERIE 3", precio: 722 },
    { material: "SERIE 4", precio: 748 },
    { material: "SERIE 5", precio: 787 },
    { material: "SERIE 6", precio: 824 },
    { material: "SERIE 7", precio: 877 },
  ],
  comunAGOMME: [
    { material: "SERIE 1", precio: 577 },
    { material: "SERIE 2", precio: 596 },
    { material: "SERIE 3", precio: 616 },
    { material: "SERIE 4", precio: 634 },
    { material: "SERIE 5", precio: 662 },
    { material: "SERIE 6", precio: 691 },
    { material: "SERIE 7", precio: 730 },
  ],
  comunAGOMMEDI: [
    { material: "SERIE 1", precio: 577 },
    { material: "SERIE 2", precio: 596 },
    { material: "SERIE 3", precio: 616 },
    { material: "SERIE 4", precio: 634 },
    { material: "SERIE 5", precio: 662 },
    { material: "SERIE 6", precio: 691 },
    { material: "SERIE 7", precio: 730 },
  ],
  comunAGOMXL: [
    { material: "SERIE 1", precio: 613 },
    { material: "SERIE 2", precio: 634 },
    { material: "SERIE 3", precio: 654 },
    { material: "SERIE 4", precio: 675 },
    { material: "SERIE 5", precio: 706 },
    { material: "SERIE 6", precio: 736 },
    { material: "SERIE 7", precio: 779 },
  ],
  comunAGOMXLDI: [
    { material: "SERIE 1", precio: 734 },
    { material: "SERIE 2", precio: 763 },
    { material: "SERIE 3", precio: 790 },
    { material: "SERIE 4", precio: 819 },
    { material: "SERIE 5", precio: 860 },
    { material: "SERIE 6", precio: 902 },
    { material: "SERIE 7", precio: 958 },
  ],
  comunAGOR: [
    { material: "SERIE 1", precio: 628 },
    { material: "SERIE 2", precio: 653 },
    { material: "SERIE 3", precio: 678 },
    { material: "SERIE 4", precio: 703 },
    { material: "SERIE 5", precio: 741 },
    { material: "SERIE 6", precio: 779 },
    { material: "SERIE 7", precio: 829 },
  ],
  comunAGORTDI: [
    { material: "SERIE 1", precio: 955 },
    { material: "SERIE 2", precio: 993 },
    { material: "SERIE 3", precio: 1031 },
    { material: "SERIE 4", precio: 1068 },
    { material: "SERIE 5", precio: 1124 },
    { material: "SERIE 6", precio: 1180 },
    { material: "SERIE 7", precio: 1125 },
  ],
  comunAGOTGRDI: [
    { material: "SERIE 1", precio: 658 },
    { material: "SERIE 2", precio: 678 },
    { material: "SERIE 3", precio: 698 },
    { material: "SERIE 4", precio: 718 },
    { material: "SERIE 5", precio: 749 },
    { material: "SERIE 6", precio: 779 },
    { material: "SERIE 7", precio: 819 },
  ],
  comunAGOTMADI: [
    { material: "SERIE 1", precio: 679 },
    { material: "SERIE 2", precio: 701 },
    { material: "SERIE 3", precio: 722 },
    { material: "SERIE 4", precio: 742 },
    { material: "SERIE 5", precio: 773 },
    { material: "SERIE 6", precio: 804 },
    { material: "SERIE 7", precio: 846 },
  ],
  comunAGOTMEDI: [
    { material: "SERIE 1", precio: 731 },
    { material: "SERIE 2", precio: 755 },
    { material: "SERIE 3", precio: 779 },
    { material: "SERIE 4", precio: 803 },
    { material: "SERIE 5", precio: 839 },
    { material: "SERIE 6", precio: 874 },
    { material: "SERIE 7", precio: 923 },
  ],
  comunAGOT2RGDI: [
    { material: "SERIE 1", precio: 954 },
    { material: "SERIE 2", precio: 985 },
    { material: "SERIE 3", precio: 1016 },
    { material: "SERIE 4", precio: 1047 },
    { material: "SERIE 5", precio: 1093 },
    { material: "SERIE 6", precio: 1139 },
    { material: "SERIE 7", precio: 1200 },
  ],
  comunAGO3: [
    { material: "SERIE 1", precio: 1104 },
    { material: "SERIE 2", precio: 1154 },
    { material: "SERIE 3", precio: 1204 },
    { material: "SERIE 4", precio: 1253 },
    { material: "SERIE 5", precio: 1328 },
    { material: "SERIE 6", precio: 1402 },
    { material: "SERIE 7", precio: 1504 },
  ],
  comunAGO3DI: [
    { material: "SERIE 1", precio: 962 },
    { material: "SERIE 2", precio: 1004 },
    { material: "SERIE 3", precio: 1047 },
    { material: "SERIE 4", precio: 1090 },
    { material: "SERIE 5", precio: 1153 },
    { material: "SERIE 6", precio: 1216 },
    { material: "SERIE 7", precio: 1302 },
  ],
  comunAGO35DI: [
    { material: "SERIE 1", precio: 1015 },
    { material: "SERIE 2", precio: 1057 },
    { material: "SERIE 3", precio: 1100 },
    { material: "SERIE 4", precio: 1142 },
    { material: "SERIE 5", precio: 1206 },
    { material: "SERIE 6", precio: 1270 },
    { material: "SERIE 7", precio: 1354 },
  ],
};
const piezas = [
  {
    id: "None",
    title: "---Sin pieza seleccionada--",
    imageUrl: "..",
  },
  {
    id: "YUTCGRD",
    title: "YUTCGRD Chaise longue grande (104 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/CH_80_DER.png",
    price: precios.comunYUTCGR,
    medida: 104,
  },
  {
    id: "YUTCGRI",
    title: "YUTCGRI Chaise longue grande (104 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/CH_80_IZQ.png",
    price: precios.comunYUTCGR,
    medida: 104,
  },
  {
    id: "YUTCMAD",
    title: "YUTCMAD Chaise longue maxi (114 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/CH_90_DER.png",
    price: precios.comunYUTCMA,
    medida: 114,
  },
  {
    id: "YUTCMAI",
    title: "YUTCMAI Chaise longue maxi (114 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/CH_90_IZQ.png",
    price: precios.comunYUTCMA,
    medida: 114,
  },
  {
    id: "YUTCMED",
    title: "YUTCMED Chaise longue mega (124 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/CH_100_DER.png",
    price: precios.comunYUTCME,
  },
  {
    id: "YUTCMEI",
    title: "YUTCMEI Chaise longue mega (124 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/CH_100_IZQ.png",
    price: precios.comunYUTCME,
  },
  {
    id: "YUTMGR",
    title: "YUTMGR Módulo grande (80 cm) sin brazo",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M80_SB.png",
    price: precios.comunYUTMGR,
  },
  {
    id: "YUTMGRD",
    title: "YUTMGRD Módulo grande (104 cm) brazo dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M80_DER.png",
    price: precios.comunYUTMGRDI,
  },
  {
    id: "YUTMGRI",
    title: "YUTMGRI Módulo grande (104 cm) brazo izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M80_IZQ.png",
    price: precios.comunYUTMGRDI,
  },
  {
    id: "YUTMMAD",
    title: "YUTMMAD Módulo maxi (114 cm) brazo dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M90_DER.png",
    price: precios.comunYUTMMADI,
  },
  {
    id: "YUTMMAI",
    title: "YUTMMAI Módulo maxi (114 cm) brazo izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M90_IZQ.png",
    price: precios.comunYUTMMADI,
  },
  {
    id: "YUTMME",
    title: "YUTMME Módulo mega (100 cm) sin brazo",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M100_SB.png",
    price: precios.comunYUTMME,
  },
  {
    id: "YUTMMED",
    title: "YUTMMED Módulo mega (124 cm) brazo dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M100_DER.png",
    price: precios.comunYUTMMEDI,
  },
  {
    id: "YUTMMEI",
    title: "YUTMMEI Módulo mega (124 cm) brazo izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M100_IZQ.png",
    price: precios.comunYUTMMEDI,
  },
  {
    id: "YUTMXL",
    title: "YUTMXL Módulo XL (110 cm) sin brazo",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M110_SB.png",
    price: precios.comunYUTMXL,
  },
  {
    id: "YUTMXLD",
    title: "YUTMXLD Módulo XL (134 cm) brazo dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M110_DER.png",
    price: precios.comunYUTMXLDI,
  },
  {
    id: "YUTMXLI",
    title: "YUTMXLI Módulo XL (134 cm) brazo izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/M110_IZQ.png",
    price: precios.comunYUTMXLDI,
  },
  {
    id: "YUTRA",
    title: "YUTRA Rincón abierto (113 x 113 cm)",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/RA.png",
    price: precios.comunYUTRA,
  },
  {
    id: "YUTRTD",
    title: "YUTRTD Rincón terminal derecho (108 x 205 cm)",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/RT_DER.png",
    price: precios.comunYUTRT,
  },
  {
    id: "YUTRTI",
    title: "YUTRTI Rincón terminal izquierdo (108 x 205 cm)",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/RT_IZQ.png",
    price: precios.comunYUTRT,
  },
  {
    id: "YUTTGRD",
    title: "YUTTGRD Terminal grande (123 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/TER_80_DER.png",
    price: precios.comunYUTTGR,
  },
  {
    id: "YUTTGRI",
    title: "YUTTGRI Terminal grande (123 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/TER_80_IZQ.png",
    price: precios.comunYUTTGR,
  },
  {
    id: "YUTTMAD",
    title: "YUTTMAD Terminal maxi (133 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/TER_90_DER.png",
    price: precios.comunYUTTMA,
  },
  {
    id: "YUTTMAI",
    title: "YUTTMAI Terminal maxi (133 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/YUTE/TER_90_IZQ.png",
    price: precios.comunYUTTMA,
  },
];
/*-------------------PIEZAS LINO--------------------*/
const piezasLino = [
  {
    id: "None",
    title: "---Sin pieza seleccionada--",
    imageUrl: "..",
  },
  {
    id: "LINCGRD",
    title: "LINCGRD Chaise longue grande (104 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/CH_80_DER.png",
    price: preciosLino.comunLINCGR,
    medida: 104,
  },
  ,
  {
    id: "LINCGRI",
    title: "LINCGRI Chaise longue grande (104 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/CH_80_IZQ.png",
    price: preciosLino.comunLINCGR,
    medida: 104,
  },
  {
    id: "LINCMAD",
    title: "LINCMAD Chaise longue maxi (114 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/CH_90_DER.png",
    price: preciosLino.comunLINCMA,
    medida: 114,
  },
  {
    id: "LINCMAI",
    title: "LINCMAI Chaise longue maxi (114 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/CH_90_IZQ.png",
    price: preciosLino.comunLINCMA,
    medida: 114,
  },
  /*--------PIEZAS MEDIANAS-------*/
  {
    id: "LINCMDD",
    title: "LINCMDD Chaise longue mediano (94 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/CH_70_DER.png",
    price: preciosLino.comunLINCMD,
    medida: 94,
  },
  {
    id: "LINCMDI",
    title: "LINCMDI Chaise longue mediano (94 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/CH_70_IZQ.png",
    price: preciosLino.comunLINCMD,
    medida: 94,
  },
  {
    id: "LINMMDD",
    title: "LINMMDD modulo mediano (94 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M70_DER.png",
    price: preciosLino.comunLINMMDI,
    medida: 94,
  },
  {
    id: "LINMMDI",
    title: "LINMMDI modulo mediano (94 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M70_IZQ.png",
    price: preciosLino.comunLINMMDI,
    medida: 94,
  },
  {
    id: "LINMMD",
    title: "LINMMD modulo mediano sin brazo (70 cm).",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M70_SB.png",
    price: preciosLino.comunLINMMD,
    medida: 94,
  },
  /*--------ARRIBA MEDIANAS-------*/
  {
    id: "LINCMED",
    title: "LINCMED Chaise longue mega (124 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/CH_100_DER.png",
    price: preciosLino.comunLINCME,
  },
  {
    id: "LINCMEI",
    title: "LINCMEI Chaise longue mega (124 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/CH_100_IZQ.png",
    price: preciosLino.comunLINCME,
  },
  {
    id: "LINMGR",
    title: "LINMGR Módulo grande (80 cm) sin brazo",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M80_SB.png",
    price: preciosLino.comunLINMGR,
  },
  {
    id: "LINMGRD",
    title: "LINMGRD Módulo grande (104 cm) brazo dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M80_DER.png",
    price: preciosLino.comunLINMGRDI,
  },
  {
    id: "LINMGRI",
    title: "LINMGRI Módulo grande (104 cm) brazo izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M80_IZQ.png",
    price: preciosLino.comunLINMGRDI,
  },
  {
    id: "LINMMA",
    title: "LINMMA Módulo maxi (90 cm) sin brazo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M90_SB.png",
    price: preciosLino.comunLINMMA,
  },
  {
    id: "LINMMAD",
    title: "LINMMAD Módulo maxi (114 cm) brazo dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M90_DER.png",
    price: preciosLino.comunLINMMADI,
  },
  {
    id: "LINMMAI",
    title: "LINMMAI Módulo maxi (114 cm) brazo izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M90_IZQ.png",
    price: preciosLino.comunLINMMADI,
  },
  {
    id: "LINMME",
    title: "LINMME Módulo mega (100 cm) sin brazo",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M100_SB.png",
    price: preciosLino.comunLINMME,
  },
  {
    id: "LINMMED",
    title: "LINMMED Módulo mega (124 cm) brazo dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M100_DER.png",
    price: preciosLino.comunLINMMEDI,
  },
  {
    id: "LINMMEI",
    title: "LINMMEI Módulo mega (124 cm) brazo izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M100_IZQ.png",
    price: preciosLino.comunLINMMEDI,
  },
  {
    id: "LINMXL",
    title: "LINMXL Módulo XL (110 cm) sin brazo",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M110_SB.png",
    price: preciosLino.comunLINMXL,
  },
  {
    id: "LINMXLD",
    title: "LINMXLD Módulo XL (134 cm) brazo dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M110_DER.png",
    price: preciosLino.comunLINMXLDI,
  },
  {
    id: "LINMXLI",
    title: "LINMXLI Módulo XL (134 cm) brazo izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/M110_IZQ.png",
    price: preciosLino.comunLINMXLDI,
  },
  {
    id: "LINRA",
    title: "LINRA Rincón abierto (113 x 113 cm)",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/RA.png",
    price: preciosLino.comunLINRA,
  },
  {
    id: "LINRTD",
    title: "LINRTD Rincón terminal derecho (108 x 205 cm)",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/RT_DER.png",
    price: preciosLino.comunLINRTDI,
  },
  {
    id: "LINRTI",
    title: "LINRTI Rincón terminal izquierdo (108 x 205 cm)",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/RT_IZQ.png",
    price: preciosLino.comunLINRTDI,
  },
  {
    id: "LINTGRD",
    title: "LINTGRD Terminal grande (123 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/TER_80_DER.png",
    price: preciosLino.comunLINTGRDI,
  },
  {
    id: "LINTGRI",
    title: "LINTGRI Terminal grande (123 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/TER_80_IZQ.png",
    price: preciosLino.comunLINTGRDI,
  },
  {
    id: "LINTMAD",
    title: "LINTMAD Terminal maxi (133 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/TER_90_DER.png",
    price: preciosLino.comunLINTMADI,
  },
  {
    id: "LINTMAI",
    title: "LINTMAI Terminal maxi (133 cm) izqdo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/LINO/TER_90_IZQ.png",
    price: preciosLino.comunLINTMADI,
  },
];
/*-------------------PIEZAS AGORA--------------------*/
const piezasAgora = [
  {
    id: "None",
    title: "---Sin pieza seleccionada--",
    imageUrl: "..",
  },
  {
    id: "AGOCGRD",
    title: "AGOCGRD Chaise longue grande (104 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/CH_80_DER.png",
    price: preciosAgora.comunAGOCGR,
    medida: 104,
  },
  {
    id: "AGOCGRI",
    title: "AGOCGRI Chaise longue grande (104 cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/CH_80_IZQ.png",
    price: preciosAgora.comunAGOCGR,
    medida: 104,
  },
  {
    id: "AGOCMAD",
    title: "AGOCMAD Chaise longue maxi (114 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/CH_90_DER.png",
    price: preciosAgora.comunAGOCMA,
    medida: 104,
  },
  {
    id: "AGOCMAI",
    title: "AGOCMAI Chaise longue maxi (114 cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/CH_90_IZQ.png",
    price: preciosAgora.comunAGOCMA,
    medida: 104,
  },
  {
    id: "AGOCMED",
    title: "AGOCMAD Chaise longue mega (124 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/CH_100_DER.png",
    price: preciosAgora.comunAGOCME,
    medida: 104,
  },
  {
    id: "AGOCMEI",
    title: "AGOCMAI Chaise longue mega (124 cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/CH_100_IZQ.png",
    price: preciosAgora.comunAGOCME,
    medida: 104,
  },
  {
    id: "AGOMGR",
    title: "AGOMGR modulo grande (80 cm) sin brazo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M80_SB.png",
    price: preciosAgora.comunAGOMGR,
    medida: 80,
  },
  {
    id: "AGOMGRD",
    title: "AGOMGRD modulo grande (104 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M80_DER.png",
    price: preciosAgora.comunAGOMGRDI,
    medida: 80,
  },
  {
    id: "AGOMGRI",
    title: "AGOMGRI modulo grande (104 cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M80_IZQ.png",
    price: preciosAgora.comunAGOMGRDI,
    medida: 80,
  },
  {
    id: "AGOMMA",
    title: "AGOMMA modulo maxi (90 cm) sin brazo",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M90_SB.png",
    price: preciosAgora.comunAGOMMA,
    medida: 80,
  },
  {
    id: "AGOMMAD",
    title: "AGOMMAD modulo maxi (114 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M90_DER.png",
    price: preciosAgora.comunAGOMMADI,
    medida: 80,
  },
  {
    id: "AGOMMAI",
    title: "AGOMMAI modulo maxi (114 cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M90_IZQ.png",
    price: preciosAgora.comunAGOMMADI,
    medida: 80,
  },
  {
    id: "AGOMME",
    title: "AGOMME modulo mega (100 cm) sin brazo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M100_SB.png",
    price: preciosAgora.comunLINCGR,
    medida: 80,
  },
  {
    id: "AGOMMED",
    title: "AGOMMED modulo mega (124 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M100_DER.png",
    price: preciosAgora.comunAGOMMEDI,
    medida: 80,
  },
  {
    id: "AGOMMEI",
    title: "AGOMMEI modulo mega (124 cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M100_IZQ.png",
    price: preciosAgora.comunAGOMMEDI,
    medida: 80,
  },
  {
    id: "AGOMXL",
    title: "AGOMXL modulo XL (110 cm) sin brazo.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M110_SB.png",
    price: preciosAgora.comunAGOMXLDI,
    medida: 80,
  },
  {
    id: "AGOMXLD",
    title: "AGOMXLD modulo XL (110 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/M110_DER.png",
    price: preciosAgora.comunAGOMXLDI,
    medida: 80,
  },
  {
    id: "AGOR",
    title: "AGOR rincon cerrado",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/RC.png",
    price: preciosAgora.comunAGOR,
    medida: 80,
  },
  {
    id: "AGORTD",
    title: "AGORTD Rincón terminal derecho (108 x 205 cm)",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/RT_DER.png",
    price: preciosAgora.comunAGORTDI,
    medida: 80,
  },
  {
    id: "AGORTI",
    title: "AGORTI Rincón terminal grande (123 cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/RT_IZQ.png",
    price: preciosAgora.comunAGORTDI,
    medida: 80,
  },
  {
    id: "AGOTGRD",
    title: "AGOTGRD terminal grande (123 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/TER_80_DER.png",
    price: preciosAgora.comunAGOTGRDI,
    medida: 80,
  },
  {
    id: "AGOTGRD",
    title: "AGOTGRD terminal grande (123 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/TER_80_IZQ.png",
    price: preciosAgora.comunAGOTGRDI,
    medida: 80,
  },
  {
    id: "AGOTGRD",
    title: "AGOTGRD terminal grande (123 cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/RT_DER.png",
    price: preciosAgora.comunAGOTGRDI,
    medida: 80,
  },
  {
    id: "AGOTMAD",
    title: "AGOTMAD terminal maxi (133cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/TER_90_DER.png",
    price: preciosAgora.comunAGOTMADI,
    medida: 80,
  },
  {
    id: "AGOTMAI",
    title: "AGOTMAI terminal maxi (133cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/TER_90_IZQ.png",
    price: preciosAgora.comunAGOTMADI,
    medida: 80,
  },
  {
    id: "AGOTMED",
    title: "AGOTMED terminal maxi (143cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/TER_100_IZQ.png",
    price: preciosAgora.comunAGOTMEDI,
    medida: 80,
  },
  {
    id: "AGOTMEI",
    title: "AGOTMEI terminal maxi (143cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/TER_100_IZQ.png",
    price: preciosAgora.comunAGOTMEDI,
    medida: 80,
  },
  {
    id: "AGOT2RGD",
    title: "AGOT2RGD terminal doble grande (203cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/TDB_80_DER.png",
    price: preciosAgora.comunAGOT2RGDI,
    medida: 80,
  },
  {
    id: "AGOT2RGI",
    title: "AGOT2RGI terminal doble grande (203cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/TDB_80_IZQ.png",
    price: preciosAgora.comunAGOT2RGDI,
    medida: 80,
  },
  {
    id: "AGO3",
    title: "AGO3 sofa 3 plazas (208cm).",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/3PL.png",
    price: preciosAgora.comunAGO3,
    medida: 80,
  },
  {
    id: "AGO3D",
    title: "AGO3D sofa 3 plazas (184cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/3PL.png",
    price: preciosAgora.comunAGO3DI,
    medida: 80,
  },
  {
    id: "AGO3I",
    title: "AGO3I sofa 3 plazas (184cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/3PL.png",
    price: preciosAgora.comunAGO3DI,
    medida: 80,
  },
  {
    id: "AGO35D",
    title: "AGO35D sofa 3,5 plazas (204cm) dcho.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/35PL_DER.png",
    price: preciosAgora.comunAGO35DI,
    medida: 80,
  },
  {
    id: "AGO35I",
    title: "AGO35I sofa 3,5 plazas (204cm) izq.",
    imageUrl:
      "https://francokohler.github.io/Presupuestadora/assets/AGORA/35PL_IZQ.png",
    price: preciosAgora.comunAGO35DI,
    medida: 80,
  },
];
const muestras = {
  brixton: [
    { img: "assets/BRIXTON/BRIXTON_10.png", nombre: "BRIXTON_10" },
    { img: "assets/BRIXTON/BRIXTON_13.png", nombre: "BRIXTON_13" },
    { img: "assets/BRIXTON/BRIXTON_16.png", nombre: "BRIXTON_16" },
    { img: "assets/BRIXTON/BRIXTON_32.png", nombre: "BRIXTON_32 " },
    { img: "assets/BRIXTON/BRIXTON_80.png", nombre: "BRIXTON_80" },
    { img: "assets/BRIXTON/BRIXTON_101.png", nombre: "BRIXTON_101" },
    { img: "assets/BRIXTON/BRIXTON_245.png", nombre: "BRIXTON_245" },
  ],
  camila: [
    { img: "assets/CAMILA/CAMILA_10.png", nombre: "CAMILA_10" },
    { img: "assets/CAMILA/CAMILA_28.png", nombre: "CAMILA_28" },
    { img: "assets/CAMILA/CAMILA_32.png", nombre: "CAMILA_32" },
    { img: "assets/CAMILA/CAMILA_51.png", nombre: "CAMILA_51" },
    { img: "assets/CAMILA/CAMILA_53.png", nombre: "CAMILA_53" },
    { img: "assets/CAMILA/CAMILA_56.png", nombre: "CAMILA_56" },
    { img: "assets/CAMILA/CAMILA_60.png", nombre: "CAMILA_60" },
    { img: "assets/CAMILA/CAMILA_90.png", nombre: "CAMILA_90" },
  ],
  montreal: [
    { img: "assets/MONTREAL/MONTREAL-01.jpg", nombre: "MONTREAL-01" },
    { img: "assets/MONTREAL/MONTREAL-02.jpg", nombre: "MONTREAL-02" },
    { img: "assets/MONTREAL/MONTREAL-03.jpg", nombre: "MONTREAL-03" },
    { img: "assets/MONTREAL/MONTREAL-04.jpg", nombre: "MONTREAL-04" },
    { img: "assets/MONTREAL/MONTREAL-05.jpg", nombre: "MONTREAL-05" },
    { img: "assets/MONTREAL/MONTREAL-06.jpg", nombre: "MONTREAL-06" },
    { img: "assets/MONTREAL/MONTREAL-07.jpg", nombre: "MONTREAL-07" },
    { img: "assets/MONTREAL/MONTREAL-08.jpg", nombre: "MONTREAL-08" },
  ],
  osaka: [
    { img: "assets/OSAKA/OSAKA-01.jpg", nombre: "OSAKA-01" },
    { img: "assets/OSAKA/OSAKA-02.jpg", nombre: "OSAKA-02" },
    { img: "assets/OSAKA/OSAKA-03.jpg", nombre: "OSAKA-03" },
    { img: "assets/OSAKA/OSAKA-04.jpg", nombre: "OSAKA-04" },
    { img: "assets/OSAKA/OSAKA-05.jpg", nombre: "OSAKA-05" },
    { img: "assets/OSAKA/OSAKA-06.jpg", nombre: "OSAKA-06" },
    { img: "assets/OSAKA/OSAKA-08.jpg", nombre: "OSAKA-08" },
  ],
  terranova: [
    { img: "assets/TERRANOVA/TERRANOVA-01.jpg", nombre: "TERRANOVA-01" },
    { img: "assets/TERRANOVA/TERRANOVA-02.jpg", nombre: "TERRANOVA-02" },
    { img: "assets/TERRANOVA/TERRANOVA-03.jpg", nombre: "TERRANOVA-03" },
    { img: "assets/TERRANOVA/TERRANOVA-04.jpg", nombre: "TERRANOVA-04" },
    { img: "assets/TERRANOVA/TERRANOVA-05.jpg", nombre: "TERRANOVA-05" },
    { img: "assets/TERRANOVA/TERRANOVA-06.jpg", nombre: "TERRANOVA-06" },
    { img: "assets/TERRANOVA/TERRANOVA-07.jpg", nombre: "TERRANOVA-07" },
    { img: "assets/TERRANOVA/TERRANOVA-08.jpg", nombre: "TERRANOVA-08" },
    { img: "assets/TERRANOVA/TERRANOVA-09.jpg", nombre: "TERRANOVA-09" },
  ],
  telaCliente: [
    { img: "assets/TELACLIENTE/Telacliente.png", nombre: "Tela Cliente" },
  ],
};
